### ISSUE TITLE
Question: Go version on Chapter 2

### ISSUE THREAD

**Issue by bossiernesto** [mhausenblas/o11y-in-action.cloud#1]
I've been reviewing the manuscript and code and on chapter 2, i've seen that the modules are using the 1.16 Go version, for eg. https://github.com/mhausenblas/o11y-in-action.cloud/blob/main/code/ch02/logs/go.mod#L3

Is there any reason why this version was chosen?  I've been testing with 1.16, 1.18 and 1.20 and all three versions seem to run fine. I was just thinking on leaving the latests stable version as the 1.16 version is now unsupported in https://endoflife.date/go

**Comment by mhausenblas** [comment]
No reason other than that's what I had installed on my machine at the time. Thanks for pointing this out and agreed we should standardize on 1.20 across the book.
